apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx # Selects pods with label app: nginx
  ports:
  - port: 80
    name: web
  clusterIP: None # Headless service, service will not get a cluster IP, will use DNS for pod discovery
