apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx" # Must match the name of the headless service
  replicas: 2
  selector:
    matchLabels:
      app: nginx # Must match the label in the pod template
  template:
    metadata:
      labels:
        app: nginx # Label for the pods
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.2
        ports:
        - containerPort: 80
          name: web