apiVersion: v1
kind: Pod
metadata:
  name: host-aliases-demo
spec:
  restartPolicy: Never

  hostAliases:
  - ip: "10.1.2.3"
    hostnames:
      - "foo.remote"
      - "bar.remote"

  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers:
    - name: init-data
      image: debian
      command: ["/bin/sh", "-c"]
      args:
        - echo Hello from the debian container > /pod-data/index.html
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data

  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html